-- Community Hub V18 — run once in Supabase Dashboard > SQL Editor
-- Public visitors can read/post. Only the verified owner can delete.

create table if not exists public.community_messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  client_id text not null check (char_length(client_id) between 8 and 100),
  display_name text not null check (char_length(display_name) between 2 and 32),
  body text not null default '' check (char_length(body) <= 4000),
  reply_to bigint references public.community_messages(id) on delete set null,
  media jsonb not null default '[]'::jsonb,
  is_ai boolean not null default false
);

alter table public.community_messages enable row level security;

drop policy if exists "public can read community messages" on public.community_messages;
create policy "public can read community messages" on public.community_messages
for select to anon, authenticated using (true);

drop policy if exists "public can post community messages" on public.community_messages;
create policy "public can post community messages" on public.community_messages
for insert to anon, authenticated with check (
  char_length(display_name) between 2 and 32
  and char_length(body) <= 4000
  and jsonb_typeof(media) = 'array'
  and jsonb_array_length(media) <= 3
);

drop policy if exists "owner can delete community messages" on public.community_messages;
create policy "owner can delete community messages" on public.community_messages
for delete to authenticated
using (lower(coalesce(auth.jwt() ->> 'email','')) = 'sam.kazmi0090@gmail.com');

grant select, insert, delete on public.community_messages to anon, authenticated;
grant usage, select on sequence public.community_messages_id_seq to anon, authenticated;

do $$ begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='community_messages') then
    alter publication supabase_realtime add table public.community_messages;
  end if;
end $$;

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types) values (
 'community-media','community-media',true,12582912,
 array['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm','audio/webm','audio/mpeg','audio/wav','audio/ogg','audio/mp4']
) on conflict (id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "public can view community media" on storage.objects;
create policy "public can view community media" on storage.objects for select to anon,authenticated using (bucket_id='community-media');

drop policy if exists "public can upload community media" on storage.objects;
create policy "public can upload community media" on storage.objects for insert to anon,authenticated with check (bucket_id='community-media');

drop policy if exists "owner can delete community media" on storage.objects;
create policy "owner can delete community media" on storage.objects for delete to authenticated
using (bucket_id='community-media' and lower(coalesce(auth.jwt() ->> 'email',''))='sam.kazmi0090@gmail.com');
